openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test API
servers:
  - url: ${env.API_GATEWAY_URL}
  - url: ${env.CLIENT_ORIGIN}
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${env.S3_BUCKET_ID}
        object: index.html
  /{file+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${env.S3_BUCKET_ID}
        object: '{file}'
        error_object: index.html
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
  /api/{slug+}:
    x-yc-apigateway-any-method:
      parameters:
        - name: slug
          in: path
      x-yc-apigateway-integration:
        type: cloud_functions
        payload_format_version: "1.0"
        function_id: ${env.CLOUD_FUNCTION_ID}
