// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection

export enum HotsHero {
  Abathur = "abathur",
  Alarak = "alarak",
  Alexstrasza = "alexstrasza",
  Ana = "ana",
  Anduin = "anduin",
  Anubarak = "anubarak",
  Artanis = "artanis",
  Arthas = "arthas",
  Auriel = "auriel",
  Azmodan = "azmodan",
  Blaze = "blaze",
  Brightwing = "brightwing",
  Cassia = "cassia",
  Chen = "chen",
  Cho = "cho",
  Chromie = "chromie",
  Deathwing = "deathwing",
  Deckard = "deckard",
  Dehaka = "dehaka",
  Diablo = "diablo",
  Dva = "dva",
  Etc = "etc",
  Falstad = "falstad",
  Fenix = "fenix",
  Gall = "gall",
  Garrosh = "garrosh",
  Gazlowe = "gazlowe",
  Genji = "genji",
  Greymane = "greymane",
  Guldan = "guldan",
  Hanzo = "hanzo",
  Hogger = "hogger",
  Illidan = "illidan",
  Imperius = "imperius",
  Jaina = "jaina",
  Johanna = "johanna",
  Junkrat = "junkrat",
  Kaelthas = "kaelthas",
  Kelthuzad = "kelthuzad",
  Kerrigan = "kerrigan",
  Kharazim = "kharazim",
  Leoric = "leoric",
  LiLi = "li-li",
  LiMing = "li-ming",
  LtMorales = "lt-morales",
  Lucio = "lucio",
  Lunara = "lunara",
  Maiev = "maiev",
  Malfurion = "malfurion",
  Malganis = "malganis",
  Malthael = "malthael",
  Medivh = "medivh",
  Mei = "mei",
  Mephisto = "mephisto",
  Muradin = "muradin",
  Murky = "murky",
  Nazeebo = "nazeebo",
  Nova = "nova",
  Orphea = "orphea",
  Probius = "probius",
  Qhira = "qhira",
  Ragnaros = "ragnaros",
  Raynor = "raynor",
  Rehgar = "rehgar",
  Rexxar = "rexxar",
  Samuro = "samuro",
  SgtHammer = "sgt-hammer",
  Sonya = "sonya",
  Stitches = "stitches",
  Stukov = "stukov",
  Sylvanas = "sylvanas",
  Tassadar = "tassadar",
  TheButcher = "the-butcher",
  TheLostVikings = "the-lost-vikings",
  Thrall = "thrall",
  Tracer = "tracer",
  Tychus = "tychus",
  Tyrael = "tyrael",
  Tyrande = "tyrande",
  Uther = "uther",
  Valeera = "valeera",
  Valla = "valla",
  Varian = "varian",
  Whitemane = "whitemane",
  Xul = "xul",
  Yrel = "yrel",
  Zagara = "zagara",
  Zarya = "zarya",
  Zeratul = "zeratul",
  Zuljin = "zuljin"
}

export enum HotsHeroRole {
  Tank = "tank",
  Bruiser = "bruiser",
  RangedAssasin = "ranged_assasin",
  MeleeAssasin = "melee_assasin",
  Healer = "healer",
  Support = "support",
}

export const heroRoleToHeroesMap = {
  [HotsHeroRole.Tank]: [
    HotsHero.Anubarak,
    HotsHero.Arthas,
    HotsHero.Blaze,
    HotsHero.Cho,
    HotsHero.Diablo,
    HotsHero.Etc,
    HotsHero.Garrosh,
    HotsHero.Johanna,
    HotsHero.Malganis,
    HotsHero.Mei,
    HotsHero.Muradin,
    HotsHero.Stitches,
    HotsHero.Tyrael,
  ],
  [HotsHeroRole.Bruiser]: [
    HotsHero.Artanis,
    HotsHero.Chen,
    HotsHero.Deathwing,
    HotsHero.Dehaka,
    HotsHero.Dva,
    HotsHero.Gazlowe,
    HotsHero.Hogger,
    HotsHero.Imperius,
    HotsHero.Leoric,
    HotsHero.Malthael,
    HotsHero.Ragnaros,
    HotsHero.Rexxar,
    HotsHero.Sonya,
    HotsHero.Thrall,
    HotsHero.Varian,
    HotsHero.Xul,
    HotsHero.Yrel,
  ],
  [HotsHeroRole.RangedAssasin]: [
    HotsHero.Azmodan,
    HotsHero.Cassia,
    HotsHero.Chromie,
    HotsHero.Falstad,
    HotsHero.Fenix,
    HotsHero.Gall,
    HotsHero.Genji,
    HotsHero.Greymane,
    HotsHero.Guldan,
    HotsHero.Hanzo,
    HotsHero.Jaina,
    HotsHero.Junkrat,
    HotsHero.Kaelthas,
    HotsHero.Kelthuzad,
    HotsHero.LiMing,
    HotsHero.Lunara,
    HotsHero.Mephisto,
    HotsHero.Nazeebo,
    HotsHero.Nova,
    HotsHero.Orphea,
    HotsHero.Probius,
    HotsHero.Raynor,
    HotsHero.SgtHammer,
    HotsHero.Sylvanas,
    HotsHero.Tassadar,
    HotsHero.Tracer,
    HotsHero.Tychus,
    HotsHero.Valla,
    HotsHero.Zagara,
    HotsHero.Zuljin,
  ],
  [HotsHeroRole.MeleeAssasin]: [
    HotsHero.Alarak,
    HotsHero.Illidan,
    HotsHero.Kerrigan,
    HotsHero.Maiev,
    HotsHero.Murky,
    HotsHero.Qhira,
    HotsHero.Samuro,
    HotsHero.TheButcher,
    HotsHero.Valeera,
    HotsHero.Zeratul,
  ],
  [HotsHeroRole.Healer]: [
    HotsHero.Alexstrasza,
    HotsHero.Ana,
    HotsHero.Anduin,
    HotsHero.Auriel,
    HotsHero.Brightwing,
    HotsHero.Deckard,
    HotsHero.Kharazim,
    HotsHero.LiLi,
    HotsHero.LtMorales,
    HotsHero.Lucio,
    HotsHero.Malfurion,
    HotsHero.Rehgar,
    HotsHero.Stukov,
    HotsHero.Tyrande,
    HotsHero.Uther,
    HotsHero.Whitemane,
  ],
  [HotsHeroRole.Support]: [
    HotsHero.Abathur,
    HotsHero.Medivh,
    HotsHero.TheLostVikings,
    HotsHero.Zarya,
  ],
} satisfies Record<HotsHeroRole, HotsHero[]>

type ValidateAllHeroes<T extends true> = T
type AreCategoriesValid = ValidateAllHeroes<HotsHero extends { [K in HotsHeroRole]: typeof heroRoleToHeroesMap[K][number] }[HotsHeroRole] ? true : false>

export type HotsHeroToRole<T extends HotsHero> = { [K in HotsHeroRole]: T extends typeof heroRoleToHeroesMap[K][number] ? K : never }[HotsHeroRole]
